export const TIMER_STARTED = 'IZUMI/TIMER_STARTED'
export const TIMER_TICK = 'IZUMI/TIMER_TICK'
export const TIMER_PAUSED = 'IZUMI/TIMER_PAUSED'
export const TIMER_RESUMED = 'IZUMI/TIMER_RESUMED'
export const TIMER_RESET = 'IZUMI/TIMER_RESET'

export const WORK_STARTED = 'IZUMI/WORK_STARTED'
export const REST_STARTED = 'IZUMI/REST_STARTED'

export const SET_STARTED = 'IZUMI/SET_STARTED'
export const SET_COMPLETED = 'IZUMI/SET_COMPLETED'
